name: Validate

on:
  push:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install ruff
        run: pip install ruff
        shell: bash

      - name: Lint
        run: ruff check --format=github --exit-zero .
        shell: bash
